name: BRUIN_PIPELINE
schedule: "daily"
start_date: "2024-01-01"

asset_root: assets

default_connections:
  duckdb: duckdb-default

variables:
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow"]
